name: 'Build Image'
description: 'Build and push Docker image for each platform.'

inputs:
  oci_registry_username:
    description: 'DockerHub username'
    required: true
  oci_registry_password:
    description: 'DockerHub password'
    required: true
  ociBlocks:
    description: 'OCI blocks to build example: dev, runtime'
    required: true
  directory:
    description: 'The directory to operate in. Defaults to root of the repository.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download meta bake definition
      uses: actions/download-artifact@v4
      with:
        name: bake-meta
        path: /tmp

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.oci_registry_username }}
        password: ${{ inputs.oci_registry_password }}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Install bsf
      shell: bash
      run: |
        nix profile install github:buildsafedev/bsf?dir=bsf

    - name: Build and push image with digest
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        ociBlocks=(${{ inputs.ociBlocks }})
        for ociBlock in "${ociBlocks[@]}"; do
          echo "Building and pushing image for $ociBlock"
          bsf oci $ociBlock --push --digest --dest-creds=${{ inputs.oci_registry_username }}:${{ inputs.oci_registry_password }}
          digest=$(cat bsf-result/digest)
          echo "digest=$digest" >> $GITHUB_OUTPUT

          mkdir -p /tmp/digests/${ociBlock}
          touch "/tmp/digests/${ociBlock}/${digest#sha256:}"
        done

    - name: Verify digest files
      shell: bash
      run: |
        echo "Digest files created:"
        ls -l /tmp/digests

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1
